name: Build & Release Gem
on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: "Release type"
        required: true
        default: "patch"
        type: choice
        options:
          - "patch"
          - "minor"
          - "major"
jobs:
  version_bump:
    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    permissions:
      contents: write

    outputs:
      currentGemVersion: ${{ steps.current_version.outputs.CURRENT_GEM_VERSION }}
      newGemVersion: ${{ steps.new_version.outputs.NEW_GEM_VERSION }}

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Get current version
        id: current_version
        run: echo "CURRENT_GEM_VERSION=$(bin/version print)" >> $GITHUB_OUTPUT

      - name: Automated Version Bump (Ruby)
        run: bin/version bump

      - name: Get new version
        id: new_version
        run: echo "NEW_GEM_VERSION=$(bin/version print)" >> $GITHUB_OUTPUT

      - uses: stefanzweifel/git-auto-commit-action@v4

      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "${{ steps.get_version.outputs.GEM_VERSION }}"
          tag_exists_error: false
          message: "chore(ci): bump version to ${{ steps.get_version.outputs.GEM_VERSION }}"

      - run: |
          echo "Tag created: ${{ steps.tag_create.outputs.tag_exists }}"
